refactor: use the correct letter case for variables

diff --git a/shell/terminate b/shell/terminate
--- a/shell/terminate
+++ b/shell/terminate
@@ -8,18 +8,18 @@ terminate(){
         return 127
     fi
 
-	GREEN=$(tput setaf 2)
-	RED=$(tput setaf 9)
-	NC=$(tput sgr0)
+	green=$(tput setaf 2)
+	red=$(tput setaf 9)
+	no_color=$(tput sgr0)
 
-	PASS_MSG=""
-	FAIL_MSG=""
+	pass_msg=""
+	fail_msg=""
 
-	if [ -n "${2}" ]; then PASS_MSG=" ${2}"; fi
-	if [ -n "${3}" ]; then FAIL_MSG=" ${3}"; fi
+	if [ -n "${2}" ]; then pass_msg=" ${2}"; fi
+	if [ -n "${3}" ]; then fail_msg=" ${3}"; fi
 
-	if [ "${1}" = 0 ]; then echo "${GREEN}✔${PASS_MSG}${NC}";
-	else echo "${RED}❌${FAIL_MSG}${NC}" >&2; fi
+	if [ "${1}" = 0 ]; then echo "${green}✔${pass_msg}${no_color}";
+	else echo "${red}❌${fail_msg}${no_color}" >&2; fi
 
 	exit "${1}"
 }
